app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager

 
class PhotoProfile(db.Model):

   __tablename__ = 'profile_photos'

   id = db.Column(db.Integer,primary_key = True)
   pic_path = db.Column(db.String())
   user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

class Category(db.Model):
    __tablename__="categories"
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(255))


class Pitch(db.Model):
    __tablename__ = 'pitch'

    id = db.Column(db.Integer, primary_key = True )
    title = db.Column(db.String(100))
    content = db.Column(db.String(200))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    category = db.Column(db.String(255))
    
    def __repr__(self):
        return f"Pitch('{self.title}')"

    @classmethod
 
    def get_pitches(cls, category):
       pitch = Pitch.query.filter_by(category=category).all()

       return pitch
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def clear_pitch(cls):
        Pitch.all_pitchs.clear()



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    pitch = db.relationship('Pitch', backref = 'users', lazy="dynamic")
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    password = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    
   
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    
   

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    






    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length
class PostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired(), Length(min = 2, max = 45)])
    content = TextAreaField('Pitch', validators = [DataRequired()])
    category = SelectField('Pitch Category', choices=[('Inspirational','Inspirational'),('Biography','Biography'),('Business','Business'),('Ideas','Ideas')])
    submit = SubmitField('Submit')
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write your bio.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()                  
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # configure UploadSet
    configure_uploads(app,photos)
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    simple.init_app(app)
    login_manager.init_app(app)

    mail.init_app(app)
    # Will add the views and forms
    # Registering the blueprint
    # from .main import main as main_blueprint
    from .main import main as p
    app.register_blueprint(p)

    # setting config
    # from .request import configure_request
    # configure_request(app)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')



    from.post import posts as post_blueprint
    app.register_blueprint(post_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from .forms import PostForm
# from ..request import get_movies,get_movie,search_movie

from ..models import Pitch,User
from flask_login import login_required, current_user
from .forms import UpdateProfile
from .. import db,photos
import markdown2 
@main.route("/pitches")
def posts(category):
    posts=list(Pitch.query.filter_by(category=category))
    return render_template("pitches.html",posts=posts)


@main.route("/post/new", methods= ['GET', 'POST'])
@login_required
def new_post():

    form = PostForm()
    if form.validate_on_submit():
        pitch = Pitch(title=form.title.data, content = form.content.data, category = form.category.data)
        db.session.add(pitch)
        db.session.commit()
        
        return redirect(url_for('main.home'))
    return render_template('post.html',title = 'New Post', form = form, legend = 'New Post')

@main.route("/")
@main.route("/home")
def home():

   '''
   View root page function that returns the index page and its data
   '''
   title = 'Welcome to Pitch app'

   # Getting reviews by category
   page = request.args.get('page', 1, type=int)
   inspiration = Pitch.get_pitches('inspiration')
   biograghy = Pitch.get_pitches('biograghy')
   business = Pitch.get_pitches('business')

   return render_template('home.html', title=title, inspiration=inspiration, biograghy=biograghy, business=business)

@main.route('/pitches/inspiration')
def inspiration():
    posts=Pitch.query.filter_by(category='Inspirational')

    return render_template('inspirational.html', posts=posts)


@main.route('/pitches/biography')
def biograpghy():
    posts=Pitch.query.filter_by(category='Biography')

    return render_template("biograghy.html", posts=posts)
main.route('/user/<uname>/pitches')
def user_pitches(uname):
   user = User.query.filter_by(username=uname).first()
   pitches = Pitch.query.filter_by(user_id=user.id).all()
 

   return render_template("profile/pitches.html", user=user, pitches=pitches, pitches_count=pitches_count, date=user_joined)

@main.route('/pitches/idea')
def idea():

   posts=Pitch.query.filter_by(category='Ideas')

   return render_template("ideas.html", posts=posts)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.profile',uname=user.username))

    return render_template('profile/update.html',form =form)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))
@main.route('/post/<int:id>')
def single_post(id):
    post=post.query.get(id)
    if post is None:
        abort(404)
    format_post = markdown2.markdown(post.movie_review,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('post.html',post = post,format_post=format_post)
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

app/post/__init__.py
from flask import Blueprint
posts = Blueprint('posts',__name__)
from . import view,form

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}
  
  <meta http-equiv="Cache-control" content="no-cache">
 
    {{super()}}
  
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gentium+Basic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{{url_for('static', filename='css/od.css')}}">
  
  
  
    
  {% endblock %}
  

app/templates/biograghy.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <p>Biography</p>
    </div>
    {% if posts %}
   {%for posts in posts%}
    <div class="panel panel-primary">
        {{current_user.username}}
        <div class="panel-heading">{{posts.category}}</div>
        <div class="panel-body">
            {{posts.content}}
            <br>
            <br>
            </div>
    </div>
   
    {% else %}
    No post in this category yet !!
    {%endfor%}
    {% endif %}
</div>
{% endblock %}

app/templates/business.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron text-center" style="background-color: #3d7aaf; color: #fff; padding: 100px 25px;">
   <h1>business Pitches</h1>
</div>
<div class="container">
        {%if pitches %}

        {{macro.displayPitches(pitches)}}
 {%else%}
 <h4>No pitches posted</h4>
 {%endif%}
{%endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/home.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block content %}

<div class="jumbotron">
  <h1>IMPRESS US!</h1>
  <h1>Pitches</h1>
</div>

<hr>
<p>In life, you only have 60 seconds to impress someone. 1 minute can make or break you. Here is your chance to shine so sign up and post your pitch and let others see</p>


<div class="container">
   <div class="row">
     <p>View others pitches</p>
       <div class="col-md-4">
           <div class="well well-lg">
               <h3>Biography Pitches</h3>
               
               <a href="{{url_for('main.biograpghy')}}" class="btn btn-primary -center">View</a>
           </div>
       </div>
       <div class="col-md-4">
        <div class="well well-lg">
            <h3>Ideas Pitches</h3>
            
            <a href="{{url_for('main.idea')}}" class="btn btn-primary -center">View</a>
        </div>
    </div>
  
       <div class="col-md-4">
           <div class="well well-lg">
               <h3>Inspiration Pitches</h3>
              
               <a href="{{url_for('main.inspiration')}}" class="btn btn-primary -center">View</a>
           </div>
       </div>
   </div>
</div>
 
  {% endblock %}

app/templates/ideas.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <p>Idea</p>
    </div>
    {% if posts %}
   {%for posts in posts%}
    <div class="panel panel-primary">
            {{current_user.username}}
        <div class="panel-heading">{{posts.category}}</div>
        <div class="panel-body">
            {{posts.content}}
            <br>
            <br>
            </div>
    </div>
   
    {% else %}
    No post in this category yet !!
    {%endfor%}
    {% endif %}
</div>
{% endblock %}

app/templates/inspirational.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <p>Inspirational</p>
    </div>
    {% if posts %}
   {%for posts in posts%}
    <div class="panel panel-primary">
        {{current_user.username}}
        <div class="panel-heading">{{posts.category}}</div>
        <div class="panel-body">
            {{posts.content}}
            <br>
            <br>
            </div>
    </div>
   
    {% else %}
    No post in this category yet !!
    {%endfor%}
    {% endif %}
</div>
{% endblock %}

app/templates/macros.html
{% macro displayCategoryList(category_list) %}
{% for category in category_list%}
  <div>
   <a href="{{url_for('main.category',id=category.id)}}"><p>{{category.name|upper}}</p></a>
  </div>

  {% endfor %}
  {% endmacro %}
  


{% macro displayPitches(pitches_list)%}
{%for pitch in pitches_list%}
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
   <div class="well well-lg">
       <h4>{{pitch.title}}</h4>
       <p>{{pitch.content| truncate(100)}}</p>
       <p>Written by: {{current_user.username}}
              
       </p>
   </div>
</div>
{%endfor%}
{%endmacro%}

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> PITCHES </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{ url_for('main.new_post')}}">New post</a></li>
                    <li style="color:white;padding:15px;">{{current_user.username}}</li>
                   
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    {%endif%}
                  </ul>
            </div>
          

        </div>
    </div>
  </body>
</html>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<body>
    <div class="container">
        <br>
        <br>
        <br>

          <div class="col-md-3 col-lg-3 col-xl-3">
            </div>
    
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 ">
                    {{ wtf.quick_form(comment_form) }}
                    {{simplemde.load}}
    
    
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3">
                {{format_comment|safe}}
            </div>

</div>
</body>



{% endblock %}

app/templates/pitches.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
<!-- Styles block -->
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <p>PITCHES</p>
    </div>
    {% if posts %}
    {% for post in posts %}
    <div class="panel panel-primary">
        <div class="panel-heading">{{post.category}}</div>
        <div class="panel-body">
            {{post.content}}
            <br>
            <br>
            </div>
    </div>
    {% endfor %}
    {% else %}
    No post in this category yet !!
    {% endif %}
</div>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">{{legend}}</legend>
          <div class="form-group">
              {{ form.title.label(class="form-control-label") }}
              {% if form.title.errors %}
                  {{ form.title(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.title.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.title(class="form-control form-control-lg") }}
              {% endif %}
          </div>
          <div class="form-group">
              {{ form.content.label(class="form-control-label") }}
              {% if form.content.errors %}
                  {{ form.content(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.content.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.content(class="form-control form-control-lg") }}
              {% endif %}
          </div>
          <div class="form-group">
              {{ form.category.label(class="form-control-label") }}
              {% if form.category.errors %}
                  {{ form.category(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.category.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.category(class="form-control form-control-lg") }}
              {% endif %}
          </div>
          <br><br>
      </fieldset>
      <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
      </div>
  </form>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user post-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="row">
  <div class="col-md-4">
    {% if user.profile_pic_path %}Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"  border-radius="50%">

    {%else%}
    <p>No profile picture</p>

    {% endif %}
  </div>
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
<div class="container">
    <div class="row">
      <div class= "col-md-4"> 
          {% if user == current_user %}
          <a href="{{url_for('main.update_profile',uname=user.username)}}">Create your bio today</a>
      {% endif %}
      </div>
      <div class="col-md-3">
<img src="https://i.pinimg.com/originals/be/e4/f5/bee4f5c81cbabbc274bf202e68a9e5e1.gif" alt="tororo" height="200px" width="200px"id="tororo">
</div>
</div>
<div class="col-md-4"> </div>
</div>

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
<div class="container"> 
    <div class="row">
      <div class= "col-md-5"> </div>
      <div class="col-md-3">
<img src="https://i.pinimg.com/originals/be/e4/f5/bee4f5c81cbabbc274bf202e68a9e5e1.gif" alt="tororo" height="200px" width="200px"id="tororo">
</div>
</div>
<div class="col-md-4"> </div>
</div>
</div>
{% endblock %}